# Generated by Django 5.2.4 on 2025-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_transaction_options_transaction_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScooterLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("income", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="levels/"),
                ),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
