# Generated by Django 5.2.4 on 2025-07-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_scooterlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="wallet",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
