# Generated by Django 5.2.4 on 2025-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile_avatar_profile_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="wallet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
