# Generated by Django 5.2.4 on 2025-07-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_profile_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
