# Generated by Django 5.2.4 on 2025-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userscooter"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telegram Username"
            ),
        ),
    ]
