# Generated by Django 5.2.4 on 2025-07-23 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_withdrawalrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата отчета"),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Общий пробег (км)",
                    ),
                ),
                (
                    "profit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Процент прибыли (%)",
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма прибыли (€)",
                    ),
                ),
                (
                    "number_of_trips",
                    models.IntegerField(verbose_name="Количество поездок"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневной отчет",
                "verbose_name_plural": "Дневные отчеты",
                "ordering": ["-report_date"],
            },
        ),
    ]
