# Generated by Django 5.2.4 on 2025-07-25 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_dailyreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScooterStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата отчета"),
                ),
                (
                    "scooter_number",
                    models.PositiveIntegerField(verbose_name="Номер самоката"),
                ),
                ("distance", models.FloatField(verbose_name="Пробег (км)")),
                (
                    "trips",
                    models.PositiveIntegerField(verbose_name="Количество поездок"),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Прибыль (€)"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Процент"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика самоката",
                "verbose_name_plural": "Статистика самокатов",
                "ordering": ["scooter_number"],
                "unique_together": {("user", "report_date", "scooter_number")},
            },
        ),
    ]
