# Generated by Django 5.2.4 on 2025-07-25 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_scooterstats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyreport",
            unique_together={("user", "report_date")},
        ),
    ]
