# Generated by Django 5.2.4 on 2025-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_dailyreport_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scooterlevel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="scooterlevel",
            name="photo",
        ),
        migrations.AddField(
            model_name="scooterlevel",
            name="expected_scooter_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="income",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
