# Generated by Django 5.2.4 on 2025-07-25 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_scooterlevel_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scooterlevel",
            options={
                "ordering": ["number"],
                "verbose_name": "Уровень самокатов",
                "verbose_name_plural": "Уровни самокатов",
            },
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="expected_scooter_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Кол-во самокатов"
            ),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="income",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Доход в день",
            ),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="number",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер уровня"),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
