# Generated by Django 5.2.4 on 2025-07-25 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userscooter_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scooterstats",
            options={
                "ordering": ["-report_date", "scooter_number"],
                "verbose_name": "Статистика самоката",
                "verbose_name_plural": "Статистика самокатов",
            },
        ),
        migrations.AlterField(
            model_name="scooterstats",
            name="distance",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Пробег (км)"
            ),
        ),
        migrations.AlterField(
            model_name="scooterstats",
            name="report_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата отчета"
            ),
        ),
        migrations.AlterField(
            model_name="scooterstats",
            name="scooter_number",
            field=models.CharField(max_length=50, verbose_name="Номер самоката"),
        ),
    ]
