# Generated by Django 5.2.4 on 2025-07-25 12:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_scooterstats_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scooterlevel",
            name="max_daily_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Макс. дневная прибыль (€)",
            ),
        ),
        migrations.AddField(
            model_name="scooterlevel",
            name="min_daily_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Мин. дневная прибыль (€)",
            ),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="income",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Ориентировочный доход в день (€)",
            ),
        ),
        migrations.AlterField(
            model_name="scooterlevel",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Цена (€)",
            ),
        ),
    ]
