# Generated by Django 5.2.4 on 2025-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_scooterlevel_max_daily_profit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scooterlevel",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание преимуществ этого уровня",
                verbose_name="Описание уровня",
            ),
        ),
        migrations.AddField(
            model_name="scooterlevel",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="levels/", verbose_name="Фото уровня"
            ),
        ),
    ]
