# Generated by Django 5.2.4 on 2025-08-11 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_scooterlevel_description_scooterlevel_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="report_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата отчета"
            ),
        ),
    ]
