# Generated by Django 5.2.4 on 2026-02-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_dailyreport_report_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="report_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата отчета"),
        ),
    ]
